contrib sklearnSVD-TfSVD files
mlsquare/mlsquare pull request #15
Opened 2019-11-28 13:44 UTC by leoninekev

2019-11-28 14:42 UTC, dhavala approved these changes

2019-11-28 14:42 UTC, dhavala approved these changes

2019-11-28 14:43 UTC, dhavala approved these changes

2019-11-28 14:45 UTC, dhavala requested changes
all the logic went into adapter at sklearndecompose. creating new adapters should be done very rarely. in this case, creating an adapter for sklearn SVD seems unnecessary. sklearn-svd is actually based on sklearn base model class. try not creating sklearndecompose class

2019-11-28 14:47 UTC, dhavala requested changes
this new class in adapters is probably unnecessary. try implementing without this adapter, and instead use keras-regressor. you can create a new class model in architecture, just like we have GeneralizedLinearModel for all GLMs (logisticsic, linear, SVM etc). All core model logic went into this adapter.

2019-11-28 14:48 UTC, dhavala approved these changes

2019-11-28 14:48 UTC, dhavala approved these changes

2019-11-28 14:50 UTC, dhavala approved these changes

2019-11-28 14:51 UTC, dhavala approved these changes

2019-11-28 14:51 UTC, dhavala approved these changes

2019-11-28 14:51 UTC, dhavala approved these changes

2019-11-28 14:51 UTC, dhavala approved these changes

2019-11-28 14:52 UTC, dhavala approved these changes

2019-12-02 17:52 UTC, leoninekev commented
sir, please take a look.

2019-12-04 14:34 UTC, closed without merging

2019-12-04 15:58 UTC, dhavala reviewed
1) Sementically inheriting from GeneralzedLinearModel is not making sense. What GLM about SVD, nothing. Can you not just use the BaseModel?
What is 
2) under `transform` and `fit_transform` in the SVD implementation, why are you using np.dot. Instead you should tensorflow version.

2019-12-04 15:58 UTC, dhavala commented on src/mlsquare/adapters/sklearn.py
> +        if isinstance(self.proxy_model, (sklearn.DimensionalityReductionModel)):
why are still you checking for these kind of isinstance of kind of checks? try avoiding.

2019-12-04 15:58 UTC, dhavala commented on src/mlsquare/adapters/sklearn.py
> +
entire SklearnKerasRegressor is filled with isinstance checks. This should be avoided.

2019-12-04 15:58 UTC, dhavala commented on src/mlsquare/architectures/sklearn.py
> +class DimensionalityReductionModel:
You needed 
`SkLearnTfMatrixDecompositions` as an adapter. 
and 
Define a new DimensionalityReductionModel class under architectures, which inherits from BaseModel. This should have its custom set_param or get_param.
When defining SVD class, right now it is inheriting from GLM. It is totally unnecessary.